### ISSUE TITLE
Project initial setup

### ISSUE THREAD

**Issue by OpenTechConsult** [OpenTechConsult/react-advanced-2021#1]
### react-advanced-2021 initial setup

**Goals**
Initialize the project

**Tasks**

- [ ] Create the project locally using CREA
- [ ] Link the local repo and the Github repo 
- [ ] Arrange the project 
- [ ]     1) Remove the content of index.css file
- [ ]     2) Create data.js in the source folder
- [ ]     3) Remove the content of App.js and display a minimal header content
- [ ] Commit the initial setup
- [ ] Pushing the initial commit to Github repo
