### ISSUE TITLE
Conditional Rendering - Multiple returns

### ISSUE THREAD

**Issue by OpenTechConsult** [OpenTechConsult/react-advanced-2021#10]
### Conditional Rendering - Multiple returns

**Goals**
We know that a component is nothing but a function. And a function takes pieces of data, processes it, and returns something. A function can have one **return** statement inside (most common), have no **return** statement (or return undefined or void. In the case of React, it produces a big fat error, or a function can have a multiple **return** statement

**Tasks**
- [ ] Create the MultipleReturn functional component in the file multiple-return.js
- [ ] In the component let's place two `return` statements. We will notice that the first return that is hit is executed and the second one is ignored.
- [ ] In the created component, import useState, and useEffect hooks
- [ ] Let's declare a state variable `isLoading` (const [loading, setLoading] = useState()) and set its initial value to true.
- [ ] After having the isLoading value, set up a condition based on the isLoading value. (e.g. if isLoading is true then return an h2 tag text of **is loading** otherwise, return an h2 tag of text **multiple returns**
- [ ] Based on the example above, let perform a more complex on where we will perform data fetching based on the loading state, the error state, the final state
