### ISSUE TITLE
Show-Hide Component

### ISSUE THREAD

**Issue by OpenTechConsult** [OpenTechConsult/react-advanced-2021#12]
### Show-Hide Component

**Goals**
Experiment with the use of the ternary operator to display components based on a certain condition or based on a state variable.

**Tasks***

- [ ] Create the **ShowHide** component in show-hide.js file
- [ ] Create the **show** state variable using the useState hook
- [ ] Change the return statement to return a fragment and inside that fragment, place a button with a _className_ of '_btn_' and with an `onClick` event that is set to an inline function that called the `setShow` state function to which we give the opposite of the state show value 
```jsx
<button className="btn" onClick={()=> setShow(!show)}>Show/Hide</button>
```
- [ ] Now depending on the show value we are going to show or hide another react component. So we create another component called Item
```jsx
const Item = () => {
    return <div style={{marginTop:'2rem'}}>
        <h1>Window</h1>
        <h2>Size: </h2>
    </div>
}
```

- [ ] Then in the ShowHide component, we implement the logic of showing or hiding the Item component based on the **show** state variable value. Beneath the `<button ...></button>` place the following syntax
```jsx
{show &&  <Item/>
```
The example is important because firstly it shows that we are not limited to displaying HTML elements but that we can display JSX components. 
Secondly, because it demonstrates the fact that we need a cleanup function when we set up some kind of side effect that needs to be cleaned up.
- [ ] Within the Item component, set up the **size** state variable using useState.
`const [size, setSize] = useState(window.innerWidth)`
- [ ] Set up a useEffect that triggers every time we render the component
```jsx
const checkSize = () => {
    setSize(window.innerWidth);
}

useEffect(() => {
    window.addEventListener('resize', checkSize);
}, []);
```
In this particular case, we have a problem because anytime we toggle the show and hide button we call the useEffect hook (which causes the _resize_ event listener to trigger) because the Item component gets rerendered. This is not the behavior that we want. That's why we need to implement a cleanup function that is triggered every time the component is removed.
- [ ] implement the cleanup function that gets triggered every the Item component is removed from the DOM. Inside the **useEffect** function in the **Item** component, after the `window.addEventListener('resize', checkSize);` line, add the following cleanup function
```jsx
return () => {
    window.removeEventListener('resize', checkSize);
}
```
