### ISSUE TITLE
Forms - Controlled input

### ISSUE THREAD

**Issue by OpenTechConsult** [OpenTechConsult/react-advanced-2021#13]
### Forms - Controlled input

**Goals**
We are going to cover **controlled input** what they are, how they work. And also how we can set up multiple inputs with just one function. But before we get into what controlled functions are and how they work, we are going to cover the forms and how they work in React.

**Tasks**

- [ ] Create the ControlledInputs react component in the controlled-inputs.js file
- [ ]  In the root App component, import the ControlledInput component and place the component inside the App component

In React forms input values can be hooked up to a state value. To demonstrate that, let's change the ControlledInput component to look like the following

```jsx
import React, { useState } from React;

const ControlledInputs = ()=> {
    return <>
        <article>
            <form className="form">
                <div className="form-control">
                    <label htmlFor="firstName">Name:</label>
                    <input type="text" id="firstName" name="firstName"/>
                </div>
                <div className="form-control">
                    <label htmlFor="email">Name:</label>
                    <input type="text" id="email" name="email"/>
                </div>
                <button type="submit">add person</button>
            </form>
      </article>
    </>
}
```

When it comes to React we have two options for handling form submissions.
- Either we can add _onSubmit_  on the form
- Or we  can add _onClick_ on the button
We'll see how both of them work in this example

- [ ] On the `<form className="form">` line add the onSubmit event listener like so
```jsx
 <form className="form" onSubmit={handleSubmit}>
```
- [ ] Just on top of the **return** statement, let's create the handleSubmit handler function like so:
```jsx
const handleSubmit = (e) => {
    console.log('Hello World');
}
return ...
```
what happens is that when we fill the form and click the submit button, nothing happens. No **hello world** message prints on the console. The reason is that by default, the browser will try to submit the form and then refresh the page. That's why we don't see the hello world. In JavaScript, we have access to a method called preventDefault of the event **e** object which allows us to prevent the browser to deal with the form submission, and that we will take of that ourselves.
```jsx
const handleSubmit = (e) => {
    e.preventDefault();
    console.log('Hello World');
}
return ...
```
We can also set up the same behavior by using leveraging the onClick event on the button element. 
```jsx
....
const ControlledInputs = ()=> {
                .....
                <button type="submit" onClick={handleSubmit}>add person</button>
               .....
}
```

Now let's see how we can connect our inputs to the state value. We want to access the data that is inside inputs elements as we are typing or as we are submitting them. The way we do that in React is to set up state value and to add two attributes on the input elements:  **value** that will reference the state value and **onChange** event that will fire a callback function each time we type in something the input.

- [ ] Let's start by setting up our state value
```jsx
const [firstName, setFirstName] = useState('');
const [email, setEmail] = useState('');
```

- [ ] Let's head to our form input elements and add **value** and **onChange** attribute. The **value** attribute will have for value a reference to a state value like so : 
```jsx
....
const ControlledInputs = ()=> {
              const [firstName, setFirstName] = useState('');
               .....
               
               <input type="text" id="firstName" name="firstName" value={firstName}/>
               <input type="text" id="email" name="email" value={email}/>
               .....
}
```

When we do this change on the input element, providing a reference to the state variables to the input element's value attribute, we get a big fat error saying that we also need to add the onChange event handler if not the form input element will be read-only. But we need to keep in mind that we have connected the input elements values to the state variable values.

What we need to do next is to create the onChange event handler so that each time we change something in the input, we fire the function, and within that function, we set up the state value. We do it like so (we use inline function here)

```jsx
....
const ControlledInputs = ()=> {
              const [firstName, setFirstName] = useState('');
               .....
               
               <input type="text" id="firstName" name="firstName" value={firstName} onChange={(e) => setFirstName(e.target.value)} />
               <input type="text" id="email" name="email" value={email} onChange={(e) => setEmail(e.target.value)}/>
               .....
}
```

- [ ] Now we can access from the submitHandler function the input element values through the state variables

```jsx
const handleSubmit = (e) => {
    e.preventDefault();
    console.log(firstName, email);
}
return ...
```

So that's how we set up controlled input in React. We need to remember that we need a **value**  attribute that references some state variable value, and the **onChange** event listener that either reference the **setXXXX** state variable function directly or an external function in which we call the setXXXX. The setXXXX takes as argument the event target value.

To complete the issue, we want to add a feature where we can add a person (First Name and Email) to a list. Up until now we were working with external data coming from API or data that was already provided as an array. In this case, we want to be able to add data dynamically to a list. 

Since now we have a form and that we can grab the form data as we saw previously, we can proceed by creating another state variable.

- [ ] Create the state variable called **people** that we initialized with an empty array like so :
```jsx
const [people, setPeople] = useState([]);
```

- [ ] The next step is once we submit the form, we must be able to grab the form input values and add the value to the people array. But before that, we need to check the condition where the values exist and are non-empty.
```jsx
const handleSubmit = (e) => {
    e.preventDefault();
    if(firstName && email) {
       console.log('submit the form');
   }
    console.log('');
}
return ...
```
