### ISSUE TITLE
Demonstrate the use of useState() function hook

### ISSUE THREAD

**Issue by OpenTechConsult** [OpenTechConsult/react-advanced-2021#2]
### Demonstrate the use of useState()

**Goals**
This is to showcase the

**Tasks**

- [ ] Set the container class on a div element that wraps all the content rendered in the App.js (styling label)
- [ ] Create the ErrorExample component (react arrow functional component) in src/tutorial/useState folder
- [ ] Import the ErrorExample component inside the root App component and place the ErrorExample component in the container
- [ ] In the ErrorExample component, implement the logic where once we click a button a title will be changed.
