### ISSUE TITLE
Learn the basics about the use state

### ISSUE THREAD

**Issue by OpenTechConsult** [OpenTechConsult/react-advanced-2021#3]
### Learn the basics about the useState() hook

**Goals**
After seeing why we need the useState() hook see #2 , let's now actually implement the basics of useState() hook.

**Tasks**
- [ ] Create the **UseStateBasics** functional component
- [ ] Import the _useState_ from React
- [ ] Test that useState is a function my console logging it
- [ ] Test to see what the function returns. (Normally it should return an array)
- [ ] Test that we can assign the first index  of  useState() to a variable or constant
- [ ] Test that we can assign the second index value of the useState() (which is a function) to a const 
- [ ] Console log the first element and the second element of the returned array of useState() hook
- [ ] Now use array destructuring to set up the value (state) and the function that change the state
- [ ] Try out the state in the return statement of the component by displaying it in an H1 tag
- [ ] Add a button to the return statement that will be used to change the state. The button will have on click event handler
- [ ] create the eventHandler called by the onClick event and in that event, the handler calls the setter function to set the state's value
- [ ] Use conditional statement to verify the value of the **state** and change that value with **setState** otherwhise. If the state value is equal to '**_Random Title_**'  then change the state to '**_Hello World_**'. If it is already '**_Hello World_**' then we set the state to '**_Random Title_**'
- [ ]
