### ISSUE TITLE
Basic React component where the state value will be an array

### ISSUE THREAD

**Issue by OpenTechConsult** [OpenTechConsult/react-advanced-2021#4]
### Basic React component where the state value will be an array

**Goals**
Create a functional component where the state is an array. We will be able to add an item,  remove an item, etc.

**Tasks**

- [ ] Create the  React functional component called UseStateArray in which we render a simple h2 tag title
- [ ] Import data in the component
- [ ] Declare a state variable called people using useState hook (pass an empty array as the initial value of the state)
- [ ] Create the _**data.js**_ which is an array of objects. Export the array as **_data_**
- [ ] Pass the data variable exported to useState as the current value
- [ ] On the return statement, iterate over the **people** state using the map(). And for each and every person, try to console the person object and return a dummy text.
- [ ] Now we destructure the id and the name that's coming from **person**
- [ ] Then we render a  div item in which we define the key attribute with the key's value from the _id_ of the object and inside the div element we render the  name key's value
- [ ] create a button that deletes all items (on the **onClick** event we define the handle function in which we invoke the useState setter function. remember that because we need to pass a value to the useState setter function we need to pass an arrow function as the handler method. )
- [ ] work on removing individual items. create a button next to the h4. add the onClick event and create the **_removeItem_** handler function in the form of a function reference and pass the id to it. create the reference function removeItem.In the removeItem, de logic is that we want to build out an array that excludes the id passed as an argument. Use the array filter function

**Comment by OpenTechConsult** [comment]
Also, we need to remember that in the setter function we need to pass an empty array as we want to clear the state
