### ISSUE TITLE
Basic React component where the state will be an Object

### ISSUE THREAD

**Issue by OpenTechConsult** [OpenTechConsult/react-advanced-2021#5]
**Basic React component where the state will be an Object**

**Goals**
Create a functional component where a state is an object. We will see how it works

**Tasks**
- [ ] Create a React functional component called UseStateObject  in which we return a simple h2 tag title
- [ ] Declare the state variable called **_person_** using  useState hook (passing an object as its initial value `e.g. {name: 'peter', age: 24, message: 'random message'})`  (Try to console log the state variable to see if it displays the state value as it is set in the useState hook)
- [ ] Let see what happens if we change the person value. What Gotcha should we look for?.
1. In the return statement create a fragment and inside it, render 3 h3 tags. In each h3 tag call the expression to render person object attribute value.
2. Bellow the 3 tags create a button with the label _Change message_. The button has the **onClick** event with the **changeMessage** handler method
3. Define the changeMessage handler method and inside it invoke the setPerson() method to change the message to hello world. (take care of the fact that if we pass another value to the setPerson() method, it will wipe out the existing state value; the solution is to use the spread operator. `[setPerson({...person, message: 'hello world'})])`

- [ ] Let try also to use three states variables instead of using an object.
