### ISSUE TITLE
Basic React component to show case how we can work with number

### ISSUE THREAD

**Issue by OpenTechConsult** [OpenTechConsult/react-advanced-2021#6]
### Basic React component to showcase how we can work with numbers

**Goals**
- how to work with numbers
- how to set up a functional update 
- create counters. One with straight-up value and the other one will use a function

**Tasks**
- [ ] Create a function component called UseStateCounter that render a h2 text useState Counter Example
- [ ] Go to root App.js file and import the UseStateCounter component
- [ ] Go back to the UseStateCounter component and in the return statement, replace the h2 tag by fragment in which we define a section with a little bit of styling (`{{margin: '4rem 0}}`). Inside the section tag, place an h2 tag and an h1 tag. In h1 tag, place a JSX expression that target value (will be defined in the next step) (`e.g. <h1>{value}</h1>`)
- [ ] Still in UseStateCounter component before the return statement, define the state (`const [value, setValue] = useState(0)`) 
- [ ] Create three buttons. One for increasing the counter, the second is for decreasing the counter and the last is for resetting the counter. On the buttons, we will we the three flavors of event handling. the buttons responsible for increasing and decreasing the counter will use an inline arrow function. For the reset button, we will set up a reference function in which we call the setValue method and we pass 0 to init the counter.
- [ ] Now we'll see how we can pass a function to our setXXX function (functional updater form) - **1)** Grab all the section tag content and duplicate it. **2)** Keep the margin styling. **3)** Change the header h2 tag to the text _More complex counter_  **4)** The expression `{value}` in h1 tag is the same. **5)** Remove all  three buttons and create a new one  with a className of button and a text of 'increase later'  `e.g <button className="btn">increase later</button`. **6)** Let's set the onClick event to reference the **complexIncrease** function. **7)** In the **complexIncrease** function body, call the _setTimeout()_ function with as first argument an arrow function, and as second parameter the delay (e.g. 2000). **8)** In the first argument of the **setTimeout()** function (the arrow function) we call the _setValue_ function of the state variable `value` and we address the _value_ directly. **10** But we also have the possibility to pass an arrow function to the setValue() function like this `setValue((prevValue) => {  prevState + 1 })`. That allows us to use the current state value in asynchronous processing. For example in the setTimeout().
- [ ] Let use this previous  functional approach to `setXXX()` to change some handler function to use the setXXX function with an arrow function. 
- [ ]
