### ISSUE TITLE
UseEffect basics

### ISSUE THREAD

**Issue by OpenTechConsult** [OpenTechConsult/react-advanced-2021#7]
### UseEffect basics

**Goals**
Explore the basics of _useEffect_ hook

**Tasks**
- [ ] Create the React stateless component called **UseEffectBasics** in _useEffect-basics.js_. Just render a header h2 tag that displays useEffect Basics
- [ ] Import the just created **UseEffectBasics** component inside App.js
- [ ] Go to the UseEffectBasics component and import the useEffect hook from React  `import {useEffect} from React`
- [ ] call the _useEffect_ hook and pass it a callback (arrow) function as the first argument. The callback function will be called after each re-render. Test the fact that the _useEffect_ is called after each re-render of the component, by console log a text (cal _useEffect_) inside the _useEffect_ callback function, and by console log a text ('render component') outside the _useEffect_ function.
- [ ] We want to apply a side effect which will consist of changing the title of the site. We want to do it by exploiting the useEffect hook. **1)** Set up a button in the JSX where when we click the button, it will increase a counter number and we will update the page title with that a message showing the counter. The returned JSX will have an h1 tag with the counter value, a button with `onClick` event with the event handler that increment the value. **2**  In the useEffect() callback function, change the title with the following syntax (`document.title = 'New Messages(${value})'`). It uses the state value.
- [ ] change the useEffect functionality a little bit around. What if we want to show the message unless we have a counter value greater than 0. (We need to remember the rules that hooks cannot be placed in a conditional statement). One of the ways to solve that problem is to put if clause inside the useEffect function (if value > 1 only then we change the title of the value).
- [ ] let's approach the second argument of useEffect and how to use it. Let's recall that the useEffect hook takes two arguments, the first one is the callback function that implements the side effect functionality. The second argument of the useEffect hook is an array called the **list of dependencies**. When the second argument is an empty array then it means that the useEffect only runs on the initial render of the component. If we pass a state variable, then whenever that state variable is changed, then the useEffect function will run.
- [ ] explore the fact that we can use multiple useEffect inside the functional component. Let's create a second useEffect that just run on the initial render and not on the subsequent one
