### ISSUE TITLE
Clean up function

### ISSUE THREAD

**Issue by OpenTechConsult** [OpenTechConsult/react-advanced-2021#8]
### Cleanup functions, how and why we want to use them

**Goals**
Revise the cleanup function and see how and why we want to use it.

**Tasks**
- [ ] Create the functional component called UseEffectCleanup in the useEffect-cleanup.js. Inside the component, import useState and useEffect react hooks. Inside the return statement display a header 2 text indicating that we are in the right component
- [ ] In the root App component, import the **UseEffectCleanup** and return the component 
- [ ] We go back to the **UseEffectCleanup** component. What we want to do is to check the width of the window. We can do so by setting up an event listener on the `window` object
- [ ] First, we set up the state variables and their values. We set up the size state variable and as a default value, we define it as the `window.innerWidth` property. If we want to console.log we can do so a inspect the value in the console.
- [ ] Next in the return statement change the h2 tag to a fragment `<></>` in which we define a header 1 containing the title window and an h2 containing a JavaScript expression that accesses the state value `<h2>{size} PX</h2>`
- [ ] Now let's set up an event listener on the window object. And for that case, we will use the useEffect. In the useEffect callback function, let's call the `window.addEventListener()` with the event `resize` and a callback function we call `checkSize` that we'll define later
- [ ] let create the checkSize callback function (arrow function) in which we modify the state value with setSize() function
The problem with this approach is that we are going to have a bunch of event listeners that fires up. That's a problem when we have multiple components that implement event listeners like the one we implemented. We are getting this because we are changing the state value (with setSize) in the event listener handler function. That's where the cleanup function comes in handy. The cleanup function is a function returned by the useEffect() callback function in which we can do all sorts of cleanup tasks. In the present case we can remove the event listener on window object like this:  `window.removeEventListener('resize', checkSize)`
