### ISSUE TITLE
Fetch data using useEffect

### ISSUE THREAD

**Issue by OpenTechConsult** [OpenTechConsult/react-advanced-2021#9]
###  Fetch data using useEffect

**Goals**
See how to fetch data using useEffect
Fetch Github users using the useEffect function hook

**Tasks**
- [ ] Create the function component UseEffectFecthData in the useEffect-fetch-data.js file
- [ ] Import the component in the root App component 
- [ ] In the UseEffectFecthData component, declare a constant containing the Github users list API url.
- [ ] Set up a state variable called **users** using the useState hook initialized to an empty array
- [ ] In the return statement let's return a fragment composed of : h3 tag 
- [ ] Then set up the useEffect hook. In it's callback function, we make a fetch request. We have two possibilities: call the fetch method directly in the callback function or call it as part of an external function. The first method will cause an issue simply because the fetch method returns a promise which forces us to use async-await. But the problem is that we cannot use an async function inside a useEffect hook (or hook function in general). The second method is to call out the fetch() as a separate function. We do that by creating a function called `getUsers` which is an async function. Inside that function we call the fetch method to get all the github users. We console log the data to see if we have the expected results. (Don't forget to call the newly created function inside the useEffect hook)
- [ ] Next step is to call the setUsers() to change the users state variable to contains the elements we get while fetching the data
- [ ] Then inside the return statement, we create a JSX and we iterate over the user data array.

But on Gotcha, what will happen if we call the setUsers function inside the async function (`getUsers()`) destined to fetch the data. By doing so we are going to set up an infinite loop because we are changing the sate that triggers a re-render which cause the useEffect to be called which in turn call the getUsers() which also called the setUsers(). To eliminate the risk we just have to pass an array as a second argument to the useEffect hook function.
